/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.io.Console;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import model.clsDAOLocalOrderDetails;
import model.clsDAOProducts;

/**
 *
 * @author GSG
 */
public class frmLocalOrder extends javax.swing.JFrame {
    int correctIndex=0;
    model.clsDAOLocalOrderDetails localOrder;
    model.clsDAOProducts products;

    /**
     * Creates new form frmLocalOrder
     */
    public frmLocalOrder() {
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension dim = toolkit.getScreenSize();
        this.setSize(dim.width, dim.height);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        //pnlAmount.setLayout(new GridLayout(5, 3, 10, 10));
    }

    public void nameButtonsProduct() {
        localOrder = new model.clsDAOLocalOrderDetails();
        LinkedList<String[]> values = new LinkedList<String[]>();
        values = localOrder.listProducts();
        for (int i = 0; i < values.size(); i++) {
            if (values.get(i)[0] != null) {
                switch (values.get(i)[0]) {
                    case "Combo 1":
                        btnProduct1.setText(values.get(i)[0]);
                        btnProduct1.setToolTipText(values.get(i)[1] + " $ " + values.get(i)[2]);
                        break;
                    case "Combo 2":
                        btnProduct2.setText(values.get(i)[0]);
                        btnProduct2.setToolTipText(values.get(i)[1] + " $ " + values.get(i)[2]);
                        break;
                    case "Combo 3":
                        btnProduct3.setText(values.get(i)[0]);
                        btnProduct3.setToolTipText(values.get(i)[1] + " $ " + values.get(i)[2]);
                        break;
                    case "Combo 4":
                        btnProduct4.setText(values.get(i)[0]);
                        btnProduct4.setToolTipText(values.get(i)[1] + " $ " + values.get(i)[2]);

                        break;
                    case "Combo 5":
                        btnProduct5.setText(values.get(i)[0]);
                        btnProduct5.setToolTipText(values.get(i)[1] + " $ " + values.get(i)[2]);
                        break;
                    default:
                        break;
                }
            }
        }
        btnProduct6.setText(values.get(5)[0]);
        btnProduct7.setText(values.get(6)[0]);
        btnProduct8.setText(values.get(7)[0]);
        btnProduct9.setText(values.get(8)[0]);
        btnProduct6.setToolTipText(values.get(5)[1] + " $ " + values.get(5)[2]);
        btnProduct7.setToolTipText(values.get(6)[1] + " $ " + values.get(6)[2]);
        btnProduct8.setToolTipText(values.get(7)[1] + " $ " + values.get(7)[2]);
        btnProduct9.setToolTipText(values.get(8)[1] + " $ " + values.get(8)[2]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productsGroup = new javax.swing.ButtonGroup();
        numbersGroup = new javax.swing.ButtonGroup();
        actionsGroup = new javax.swing.ButtonGroup();
        pnlAmount = new javax.swing.JPanel();
        btnNumber6 = new javax.swing.JToggleButton();
        btnNumber2 = new javax.swing.JToggleButton();
        btnNumber1 = new javax.swing.JToggleButton();
        btnNumber3 = new javax.swing.JToggleButton();
        btnNumber4 = new javax.swing.JToggleButton();
        btnNumber5 = new javax.swing.JToggleButton();
        btnNumber7 = new javax.swing.JToggleButton();
        btnNumber8 = new javax.swing.JToggleButton();
        btnNumber9 = new javax.swing.JToggleButton();
        btnDoneOrder = new javax.swing.JButton();
        btnCorrection = new javax.swing.JButton();
        btnOtherAmount = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        pnlProducts = new javax.swing.JPanel();
        btnProduct1 = new javax.swing.JToggleButton();
        btnProduct2 = new javax.swing.JToggleButton();
        btnProduct3 = new javax.swing.JToggleButton();
        btnProduct4 = new javax.swing.JToggleButton();
        btnProduct5 = new javax.swing.JToggleButton();
        btnProduct6 = new javax.swing.JToggleButton();
        btnProduct8 = new javax.swing.JToggleButton();
        btnProduct9 = new javax.swing.JToggleButton();
        btnProduct7 = new javax.swing.JToggleButton();
        scrollPanelProductsTable = new javax.swing.JScrollPane();
        tblLocalOrder = new javax.swing.JTable();
        txtOrderNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1382, 744));
        setSize(new java.awt.Dimension(1382, 744));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        pnlAmount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.red)); // NOI18N
        pnlAmount.setLayout(null);

        numbersGroup.add(btnNumber6);
        btnNumber6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/numbers/iconNumber6.png"))); // NOI18N
        btnNumber6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber6ActionPerformed(evt);
            }
        });
        pnlAmount.add(btnNumber6);
        btnNumber6.setBounds(270, 120, 100, 80);

        numbersGroup.add(btnNumber2);
        btnNumber2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/numbers/iconNumber2.png"))); // NOI18N
        btnNumber2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber2ActionPerformed(evt);
            }
        });
        pnlAmount.add(btnNumber2);
        btnNumber2.setBounds(140, 30, 100, 80);

        numbersGroup.add(btnNumber1);
        btnNumber1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/numbers/iconNumber1.png"))); // NOI18N
        btnNumber1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber1ActionPerformed(evt);
            }
        });
        pnlAmount.add(btnNumber1);
        btnNumber1.setBounds(20, 30, 100, 80);

        numbersGroup.add(btnNumber3);
        btnNumber3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/numbers/iconNumber3.png"))); // NOI18N
        btnNumber3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber3ActionPerformed(evt);
            }
        });
        pnlAmount.add(btnNumber3);
        btnNumber3.setBounds(270, 30, 100, 80);

        numbersGroup.add(btnNumber4);
        btnNumber4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/numbers/iconNumber4.png"))); // NOI18N
        btnNumber4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber4ActionPerformed(evt);
            }
        });
        pnlAmount.add(btnNumber4);
        btnNumber4.setBounds(20, 120, 100, 80);

        numbersGroup.add(btnNumber5);
        btnNumber5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/numbers/iconNumber5.png"))); // NOI18N
        btnNumber5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber5ActionPerformed(evt);
            }
        });
        pnlAmount.add(btnNumber5);
        btnNumber5.setBounds(140, 120, 100, 80);

        numbersGroup.add(btnNumber7);
        btnNumber7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/numbers/iconNumber7.png"))); // NOI18N
        btnNumber7.setToolTipText("");
        btnNumber7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber7ActionPerformed(evt);
            }
        });
        pnlAmount.add(btnNumber7);
        btnNumber7.setBounds(20, 220, 100, 80);

        numbersGroup.add(btnNumber8);
        btnNumber8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/numbers/iconNumber8.png"))); // NOI18N
        btnNumber8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber8ActionPerformed(evt);
            }
        });
        pnlAmount.add(btnNumber8);
        btnNumber8.setBounds(140, 220, 100, 80);

        numbersGroup.add(btnNumber9);
        btnNumber9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/numbers/iconNumber9.png"))); // NOI18N
        btnNumber9.setToolTipText("");
        btnNumber9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber9ActionPerformed(evt);
            }
        });
        pnlAmount.add(btnNumber9);
        btnNumber9.setBounds(270, 220, 100, 80);

        btnDoneOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoneOrder.setText("Finalizar");
        btnDoneOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoneOrder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlAmount.add(btnDoneOrder);
        btnDoneOrder.setBounds(270, 310, 100, 80);

        btnCorrection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCorrection.setText("Corrección");
        btnCorrection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCorrection.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCorrection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrectionActionPerformed(evt);
            }
        });
        pnlAmount.add(btnCorrection);
        btnCorrection.setBounds(20, 400, 100, 80);

        btnOtherAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOtherAmount.setText("Otra cantidad");
        btnOtherAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOtherAmount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlAmount.add(btnOtherAmount);
        btnOtherAmount.setBounds(20, 310, 100, 80);

        btnAddProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/iconBtnAdd.png"))); // NOI18N
        btnAddProduct.setText("Agregar");
        btnAddProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        pnlAmount.add(btnAddProduct);
        btnAddProduct.setBounds(140, 310, 100, 80);

        getContentPane().add(pnlAmount);
        pnlAmount.setBounds(740, 30, 380, 490);

        pnlProducts.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.red)); // NOI18N

        productsGroup.add(btnProduct1);
        btnProduct1.setText("Combo 1");
        btnProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct1ActionPerformed(evt);
            }
        });

        productsGroup.add(btnProduct2);
        btnProduct2.setText("Combo 2");
        btnProduct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct2ActionPerformed(evt);
            }
        });

        productsGroup.add(btnProduct3);
        btnProduct3.setText("Combo 3");
        btnProduct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct3ActionPerformed(evt);
            }
        });

        productsGroup.add(btnProduct4);
        btnProduct4.setText("Combo 4");
        btnProduct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct4ActionPerformed(evt);
            }
        });

        productsGroup.add(btnProduct5);
        btnProduct5.setText("Combo 5");
        btnProduct5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct5ActionPerformed(evt);
            }
        });

        productsGroup.add(btnProduct6);
        btnProduct6.setText("Adicionales");
        btnProduct6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct6ActionPerformed(evt);
            }
        });

        productsGroup.add(btnProduct8);
        btnProduct8.setText("Producto2");
        btnProduct8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct8ActionPerformed(evt);
            }
        });

        productsGroup.add(btnProduct9);
        btnProduct9.setText("Producto3");
        btnProduct9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct9ActionPerformed(evt);
            }
        });

        productsGroup.add(btnProduct7);
        btnProduct7.setText("Producto1");
        btnProduct7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProductsLayout = new javax.swing.GroupLayout(pnlProducts);
        pnlProducts.setLayout(pnlProductsLayout);
        pnlProductsLayout.setHorizontalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProduct7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addComponent(btnProduct8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProduct9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addComponent(btnProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProduct6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlProductsLayout.setVerticalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduct8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlProducts);
        pnlProducts.setBounds(26, 30, 589, 520);

        scrollPanelProductsTable.setViewportView(tblLocalOrder);

        getContentPane().add(scrollPanelProductsTable);
        scrollPanelProductsTable.setBounds(10, 550, 1300, 130);

        txtOrderNumber.setEditable(false);
        txtOrderNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtOrderNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtOrderNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtOrderNumber);
        txtOrderNumber.setBounds(1210, 30, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Número de orden");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1180, 0, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumber6ActionPerformed

    private void btnNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumber2ActionPerformed

    private void btnNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber1ActionPerformed

    }//GEN-LAST:event_btnNumber1ActionPerformed

    private void btnNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumber3ActionPerformed

    private void btnNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumber4ActionPerformed

    private void btnNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumber5ActionPerformed

    private void btnNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumber7ActionPerformed

    private void btnNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumber8ActionPerformed

    private void btnNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumber9ActionPerformed

    private void btnProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct1ActionPerformed

    }//GEN-LAST:event_btnProduct1ActionPerformed

    private void btnProduct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct2ActionPerformed

    private void btnProduct3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct3ActionPerformed

    private void btnProduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct4ActionPerformed

    private void btnProduct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct5ActionPerformed

    private void btnProduct6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct6ActionPerformed

    private void btnProduct8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct8ActionPerformed

    private void btnProduct9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct9ActionPerformed

    private void btnProduct7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct7ActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        selectProductAndAmount();
        if (localOrder.insert()) {
            tblLocalOrder.setModel(localOrder.list());

        } else {
            JOptionPane.showMessageDialog(rootPane, "No sé insertó el producto");
        }

        PrintselectProductAndAmount();
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        nameButtonsProduct();
        localOrder = new clsDAOLocalOrderDetails();
        txtOrderNumber.setText(localOrder.selectOrderNumber());


    }//GEN-LAST:event_formWindowOpened

    private void btnCorrectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrectionActionPerformed
        correctIndex=1;
        JOptionPane.showMessageDialog(pnlAmount, "Por favor seleccione la fila del producto que desea eliminar.");
    }//GEN-LAST:event_btnCorrectionActionPerformed

    public void selectProductAndAmount() {
        if (btnProduct1.isSelected() && btnNumber1.isSelected()) {
            loadSetValuesOrderDetails(btnProduct1.getText(), 1);
        } else if (btnProduct1.isSelected() && btnNumber2.isSelected()) {
            loadSetValuesOrderDetails(btnProduct1.getText(), 2);
        } else if (btnProduct1.isSelected() && btnNumber3.isSelected()) {
            loadSetValuesOrderDetails(btnProduct1.getText(), 3);
        } else if (btnProduct1.isSelected() && btnNumber4.isSelected()) {
            loadSetValuesOrderDetails(btnProduct1.getText(), 4);
        } else if (btnProduct1.isSelected() && btnNumber5.isSelected()) {
            loadSetValuesOrderDetails(btnProduct1.getText(), 5);
        } else if (btnProduct1.isSelected() && btnNumber6.isSelected()) {
            loadSetValuesOrderDetails(btnProduct1.getText(), 6);
        } else if (btnProduct1.isSelected() && btnNumber7.isSelected()) {
            loadSetValuesOrderDetails(btnProduct1.getText(), 7);
        } else if (btnProduct1.isSelected() && btnNumber8.isSelected()) {
            loadSetValuesOrderDetails(btnProduct1.getText(), 8);
        } else if (btnProduct1.isSelected() && btnNumber9.isSelected()) {
            loadSetValuesOrderDetails(btnProduct1.getText(), 9);
        } else if (btnProduct2.isSelected() && btnNumber1.isSelected()) {
            loadSetValuesOrderDetails(btnProduct2.getText(), 1);
        } else if (btnProduct2.isSelected() && btnNumber2.isSelected()) {
            loadSetValuesOrderDetails(btnProduct2.getText(), 2);
        } else if (btnProduct2.isSelected() && btnNumber3.isSelected()) {
            loadSetValuesOrderDetails(btnProduct2.getText(), 3);
        } else if (btnProduct2.isSelected() && btnNumber4.isSelected()) {
            loadSetValuesOrderDetails(btnProduct2.getText(), 4);
        } else if (btnProduct2.isSelected() && btnNumber5.isSelected()) {
            loadSetValuesOrderDetails(btnProduct2.getText(), 5);
        } else if (btnProduct2.isSelected() && btnNumber6.isSelected()) {
            loadSetValuesOrderDetails(btnProduct2.getText(), 6);
        } else if (btnProduct2.isSelected() && btnNumber7.isSelected()) {
            loadSetValuesOrderDetails(btnProduct2.getText(), 7);
        } else if (btnProduct2.isSelected() && btnNumber8.isSelected()) {
            loadSetValuesOrderDetails(btnProduct2.getText(), 8);
        } else if (btnProduct2.isSelected() && btnNumber9.isSelected()) {
            loadSetValuesOrderDetails(btnProduct2.getText(), 9);
        } else if (btnProduct3.isSelected() && btnNumber1.isSelected()) {
            loadSetValuesOrderDetails(btnProduct3.getText(), 1);
        } else if (btnProduct3.isSelected() && btnNumber2.isSelected()) {
            loadSetValuesOrderDetails(btnProduct3.getText(), 2);
        } else if (btnProduct3.isSelected() && btnNumber3.isSelected()) {
            loadSetValuesOrderDetails(btnProduct3.getText(), 3);
        } else if (btnProduct3.isSelected() && btnNumber4.isSelected()) {
            loadSetValuesOrderDetails(btnProduct3.getText(), 4);
        } else if (btnProduct3.isSelected() && btnNumber5.isSelected()) {
            loadSetValuesOrderDetails(btnProduct3.getText(), 5);
        } else if (btnProduct3.isSelected() && btnNumber6.isSelected()) {
            loadSetValuesOrderDetails(btnProduct3.getText(), 6);
        } else if (btnProduct3.isSelected() && btnNumber7.isSelected()) {
            loadSetValuesOrderDetails(btnProduct3.getText(), 7);
        } else if (btnProduct3.isSelected() && btnNumber8.isSelected()) {
            loadSetValuesOrderDetails(btnProduct3.getText(), 8);
        } else if (btnProduct3.isSelected() && btnNumber9.isSelected()) {
            loadSetValuesOrderDetails(btnProduct3.getText(), 9);
        } else if (btnProduct4.isSelected() && btnNumber1.isSelected()) {
            loadSetValuesOrderDetails(btnProduct4.getText(), 1);
        } else if (btnProduct4.isSelected() && btnNumber2.isSelected()) {
            loadSetValuesOrderDetails(btnProduct4.getText(), 2);
        } else if (btnProduct4.isSelected() && btnNumber3.isSelected()) {
            loadSetValuesOrderDetails(btnProduct4.getText(), 3);
        } else if (btnProduct4.isSelected() && btnNumber4.isSelected()) {
            loadSetValuesOrderDetails(btnProduct4.getText(), 4);
        } else if (btnProduct4.isSelected() && btnNumber5.isSelected()) {
            loadSetValuesOrderDetails(btnProduct4.getText(), 5);
        } else if (btnProduct4.isSelected() && btnNumber6.isSelected()) {
            loadSetValuesOrderDetails(btnProduct4.getText(), 6);
        } else if (btnProduct4.isSelected() && btnNumber7.isSelected()) {
            loadSetValuesOrderDetails(btnProduct4.getText(), 7);
        } else if (btnProduct4.isSelected() && btnNumber8.isSelected()) {
            loadSetValuesOrderDetails(btnProduct4.getText(), 8);
        } else if (btnProduct4.isSelected() && btnNumber9.isSelected()) {
            loadSetValuesOrderDetails(btnProduct4.getText(), 9);
        } else if (btnProduct5.isSelected() && btnNumber1.isSelected()) {
            loadSetValuesOrderDetails(btnProduct5.getText(), 1);
        } else if (btnProduct5.isSelected() && btnNumber2.isSelected()) {
            loadSetValuesOrderDetails(btnProduct5.getText(), 2);
        } else if (btnProduct5.isSelected() && btnNumber3.isSelected()) {
            loadSetValuesOrderDetails(btnProduct5.getText(), 3);
        } else if (btnProduct5.isSelected() && btnNumber4.isSelected()) {
            loadSetValuesOrderDetails(btnProduct5.getText(), 4);
        } else if (btnProduct5.isSelected() && btnNumber5.isSelected()) {
            loadSetValuesOrderDetails(btnProduct5.getText(), 5);
        } else if (btnProduct5.isSelected() && btnNumber6.isSelected()) {
            loadSetValuesOrderDetails(btnProduct5.getText(), 6);
        } else if (btnProduct5.isSelected() && btnNumber7.isSelected()) {
            loadSetValuesOrderDetails(btnProduct5.getText(), 7);
        } else if (btnProduct5.isSelected() && btnNumber8.isSelected()) {
            loadSetValuesOrderDetails(btnProduct5.getText(), 8);
        } else if (btnProduct5.isSelected() && btnNumber9.isSelected()) {
            loadSetValuesOrderDetails(btnProduct5.getText(), 9);
        } else if (btnProduct6.isSelected() && btnNumber1.isSelected()) {
            loadSetValuesOrderDetails(btnProduct6.getText(), 1);
        } else if (btnProduct6.isSelected() && btnNumber2.isSelected()) {
            loadSetValuesOrderDetails(btnProduct6.getText(), 2);
        } else if (btnProduct6.isSelected() && btnNumber3.isSelected()) {
            loadSetValuesOrderDetails(btnProduct6.getText(), 3);
        } else if (btnProduct6.isSelected() && btnNumber4.isSelected()) {
            loadSetValuesOrderDetails(btnProduct6.getText(), 4);
        } else if (btnProduct6.isSelected() && btnNumber5.isSelected()) {
            loadSetValuesOrderDetails(btnProduct6.getText(), 5);
        } else if (btnProduct6.isSelected() && btnNumber6.isSelected()) {
            loadSetValuesOrderDetails(btnProduct6.getText(), 6);
        } else if (btnProduct6.isSelected() && btnNumber7.isSelected()) {
            loadSetValuesOrderDetails(btnProduct6.getText(), 7);
        } else if (btnProduct6.isSelected() && btnNumber8.isSelected()) {
            loadSetValuesOrderDetails(btnProduct6.getText(), 8);
        } else if (btnProduct6.isSelected() && btnNumber9.isSelected()) {
            loadSetValuesOrderDetails(btnProduct6.getText(), 9);
        } else if (btnProduct7.isSelected() && btnNumber1.isSelected()) {
            loadSetValuesOrderDetails(btnProduct7.getText(), 1);
        } else if (btnProduct7.isSelected() && btnNumber2.isSelected()) {
            loadSetValuesOrderDetails(btnProduct7.getText(), 2);
        } else if (btnProduct7.isSelected() && btnNumber3.isSelected()) {
            loadSetValuesOrderDetails(btnProduct7.getText(), 3);
        } else if (btnProduct7.isSelected() && btnNumber4.isSelected()) {
            loadSetValuesOrderDetails(btnProduct7.getText(), 4);
        } else if (btnProduct7.isSelected() && btnNumber5.isSelected()) {
            loadSetValuesOrderDetails(btnProduct7.getText(), 5);
        } else if (btnProduct7.isSelected() && btnNumber6.isSelected()) {
            loadSetValuesOrderDetails(btnProduct7.getText(), 6);
        } else if (btnProduct7.isSelected() && btnNumber7.isSelected()) {
            loadSetValuesOrderDetails(btnProduct7.getText(), 7);
        } else if (btnProduct7.isSelected() && btnNumber8.isSelected()) {
            loadSetValuesOrderDetails(btnProduct7.getText(), 8);
        } else if (btnProduct7.isSelected() && btnNumber9.isSelected()) {
            loadSetValuesOrderDetails(btnProduct7.getText(), 9);
        } else if (btnProduct8.isSelected() && btnNumber1.isSelected()) {
            loadSetValuesOrderDetails(btnProduct8.getText(), 1);
        } else if (btnProduct8.isSelected() && btnNumber2.isSelected()) {
            loadSetValuesOrderDetails(btnProduct8.getText(), 2);
        } else if (btnProduct8.isSelected() && btnNumber3.isSelected()) {
            loadSetValuesOrderDetails(btnProduct8.getText(), 3);
        } else if (btnProduct8.isSelected() && btnNumber4.isSelected()) {
            loadSetValuesOrderDetails(btnProduct8.getText(), 4);
        } else if (btnProduct8.isSelected() && btnNumber5.isSelected()) {
            loadSetValuesOrderDetails(btnProduct8.getText(), 5);
        } else if (btnProduct8.isSelected() && btnNumber6.isSelected()) {
            loadSetValuesOrderDetails(btnProduct8.getText(), 6);
        } else if (btnProduct8.isSelected() && btnNumber7.isSelected()) {
            loadSetValuesOrderDetails(btnProduct8.getText(), 7);
        } else if (btnProduct8.isSelected() && btnNumber8.isSelected()) {
            loadSetValuesOrderDetails(btnProduct8.getText(), 8);
        } else if (btnProduct8.isSelected() && btnNumber9.isSelected()) {
            loadSetValuesOrderDetails(btnProduct8.getText(), 9);
        } else if (btnProduct9.isSelected() && btnNumber1.isSelected()) {
            loadSetValuesOrderDetails(btnProduct9.getText(), 1);
        } else if (btnProduct9.isSelected() && btnNumber2.isSelected()) {
            loadSetValuesOrderDetails(btnProduct9.getText(), 2);
        } else if (btnProduct9.isSelected() && btnNumber3.isSelected()) {
            loadSetValuesOrderDetails(btnProduct9.getText(), 3);
        } else if (btnProduct9.isSelected() && btnNumber4.isSelected()) {
            loadSetValuesOrderDetails(btnProduct9.getText(), 4);
        } else if (btnProduct9.isSelected() && btnNumber5.isSelected()) {
            loadSetValuesOrderDetails(btnProduct9.getText(), 5);
        } else if (btnProduct9.isSelected() && btnNumber6.isSelected()) {
            loadSetValuesOrderDetails(btnProduct9.getText(), 6);
        } else if (btnProduct9.isSelected() && btnNumber7.isSelected()) {
            loadSetValuesOrderDetails(btnProduct9.getText(), 7);
        } else if (btnProduct9.isSelected() && btnNumber8.isSelected()) {
            loadSetValuesOrderDetails(btnProduct9.getText(), 8);
        } else if (btnProduct9.isSelected() && btnNumber9.isSelected()) {
            loadSetValuesOrderDetails(btnProduct9.getText(), 9);
        }

    }

    public void PrintselectProductAndAmount() {
        for (int i = 1; i <= 9; i++) {
            for (int j = 1; j <= 9; j++) {
                System.out.println("else if(btnProduct" + i + ".isSelected() && btnNumber" + j + ".isSelected()){\n"
                        + "loadSetValuesOrderDetails(btnProduct" + i + ".getText()," + j + ");\n}");

            }
        }
    }

    /**
     * Carga los valores de la clase products con los valores que tienen las
     * cajas de texto del JDialog products
     */
    public void loadSetValuesOrderDetails(String nameP, double amount) {
        try {
            localOrder = new clsDAOLocalOrderDetails();
            localOrder.setProduct_name(nameP);
            localOrder.setProduct_amount(amount);
            ResultSet result;
            result = localOrder.searchProductByName();
            if (result != null) {
                localOrder.setProduct_id(result.getString(1));
                localOrder.setProduct_description(result.getString(3));
                localOrder.setProduct_price(Double.parseDouble(result.getString(4)));
            }
            localOrder.setProduct_price_total(localOrder.getProduct_amount() * localOrder.getProduct_price());
        } catch (SQLException ex) {
            System.out.println(ex);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLocalOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLocalOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLocalOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLocalOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLocalOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup actionsGroup;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCorrection;
    private javax.swing.JButton btnDoneOrder;
    private javax.swing.JToggleButton btnNumber1;
    private javax.swing.JToggleButton btnNumber2;
    private javax.swing.JToggleButton btnNumber3;
    private javax.swing.JToggleButton btnNumber4;
    private javax.swing.JToggleButton btnNumber5;
    private javax.swing.JToggleButton btnNumber6;
    private javax.swing.JToggleButton btnNumber7;
    private javax.swing.JToggleButton btnNumber8;
    private javax.swing.JToggleButton btnNumber9;
    private javax.swing.JButton btnOtherAmount;
    private javax.swing.JToggleButton btnProduct1;
    private javax.swing.JToggleButton btnProduct2;
    private javax.swing.JToggleButton btnProduct3;
    private javax.swing.JToggleButton btnProduct4;
    private javax.swing.JToggleButton btnProduct5;
    private javax.swing.JToggleButton btnProduct6;
    private javax.swing.JToggleButton btnProduct7;
    private javax.swing.JToggleButton btnProduct8;
    private javax.swing.JToggleButton btnProduct9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup numbersGroup;
    private javax.swing.JPanel pnlAmount;
    private javax.swing.JPanel pnlProducts;
    private javax.swing.ButtonGroup productsGroup;
    private javax.swing.JScrollPane scrollPanelProductsTable;
    private javax.swing.JTable tblLocalOrder;
    private javax.swing.JTextField txtOrderNumber;
    // End of variables declaration//GEN-END:variables
}
