/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.Connect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author GSG
 */
public class frmReports extends javax.swing.JFrame {

    controller.Connect connexion;

    /**
     * Creates new form frmReports
     */
    public frmReports() {
        this.setUndecorated(true); //pantalla completa
        //  this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension dim = toolkit.getScreenSize();
        this.setSize(dim.width, dim.height);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReportsOrders.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgReportsOrders = new javax.swing.JDialog();
        pnlReportsOrders = new javax.swing.JPanel();
        btnDlgReportsOrdersDelivery = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnDlgReportsOrdersLocal = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnDlgAdditionsCancel = new javax.swing.JButton();
        btnReports3 = new javax.swing.JButton();
        btnAdminEmployees = new javax.swing.JButton();
        btnReports2 = new javax.swing.JButton();
        btnReports5 = new javax.swing.JButton();
        btnReports4 = new javax.swing.JButton();
        btnReportsBack = new javax.swing.JButton();
        lblBackgroundReports = new javax.swing.JLabel();

        dlgReportsOrders.setTitle("Tipo de reporte ");
        dlgReportsOrders.setMinimumSize(new java.awt.Dimension(711, 423));
        dlgReportsOrders.setSize(new java.awt.Dimension(711, 523));
        dlgReportsOrders.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dlgReportsOrdersWindowOpened(evt);
            }
        });

        pnlReportsOrders.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de reporte", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), java.awt.Color.red)); // NOI18N

        btnDlgReportsOrdersDelivery.setText("Pedidos a domicilio en un rango de días");
        btnDlgReportsOrdersDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsOrdersDeliveryActionPerformed(evt);
            }
        });

        jButton2.setText("Lista de barrios donde más piden");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");

        jButton4.setText("jButton1");

        btnDlgReportsOrdersLocal.setText("Pedidos Locales en un rango de días");
        btnDlgReportsOrdersLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsOrdersLocalActionPerformed(evt);
            }
        });

        jButton6.setText("jButton1");

        javax.swing.GroupLayout pnlReportsOrdersLayout = new javax.swing.GroupLayout(pnlReportsOrders);
        pnlReportsOrders.setLayout(pnlReportsOrdersLayout);
        pnlReportsOrdersLayout.setHorizontalGroup(
            pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDlgReportsOrdersLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReportsOrdersLayout.createSequentialGroup()
                        .addComponent(btnDlgReportsOrdersDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlReportsOrdersLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlReportsOrdersLayout.setVerticalGroup(
            pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsOrdersLayout.createSequentialGroup()
                .addGroup(pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlgReportsOrdersDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDlgReportsOrdersLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnDlgAdditionsCancel.setText("Cancelar");
        btnDlgAdditionsCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgAdditionsCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgReportsOrdersLayout = new javax.swing.GroupLayout(dlgReportsOrders.getContentPane());
        dlgReportsOrders.getContentPane().setLayout(dlgReportsOrdersLayout);
        dlgReportsOrdersLayout.setHorizontalGroup(
            dlgReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReportsOrdersLayout.createSequentialGroup()
                .addGroup(dlgReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgReportsOrdersLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnDlgAdditionsCancel))
                    .addGroup(dlgReportsOrdersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlReportsOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgReportsOrdersLayout.setVerticalGroup(
            dlgReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReportsOrdersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlReportsOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDlgAdditionsCancel))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generar reportes");
        setMinimumSize(new java.awt.Dimension(1382, 744));
        setSize(new java.awt.Dimension(1382, 744));

        btnReports3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReports3.setText("Administrar Locales");
        btnReports3.setBorderPainted(false);
        btnReports3.setContentAreaFilled(false);
        btnReports3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReports3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReports3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReports3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReports3ActionPerformed(evt);
            }
        });

        btnAdminEmployees.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        btnAdminEmployees.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdminEmployees.setText("Reportes de pedidos");
        btnAdminEmployees.setBorderPainted(false);
        btnAdminEmployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminEmployees.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdminEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminEmployeesActionPerformed(evt);
            }
        });

        btnReports2.setBackground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        btnReports2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReports2.setText("Administrar productos");
        btnReports2.setBorderPainted(false);
        btnReports2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReports2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReports2ActionPerformed(evt);
            }
        });

        btnReports5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReports5.setText("Administrar clientes");
        btnReports5.setBorderPainted(false);
        btnReports5.setContentAreaFilled(false);
        btnReports5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReports5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReports5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReports5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReports5ActionPerformed(evt);
            }
        });

        btnReports4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReports4.setText("Administrador de contraseñas");
        btnReports4.setBorderPainted(false);
        btnReports4.setContentAreaFilled(false);
        btnReports4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReports4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReports4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReports4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReports4ActionPerformed(evt);
            }
        });

        btnReportsBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReportsBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/back.png"))); // NOI18N
        btnReportsBack.setText("Volver");
        btnReportsBack.setBorderPainted(false);
        btnReportsBack.setContentAreaFilled(false);
        btnReportsBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportsBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportsBack.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReportsBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportsBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsBackActionPerformed(evt);
            }
        });

        lblBackgroundReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/555.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnAdminEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1009, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1066, 1066, 1066)
                            .addComponent(btnReports3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(btnReports4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(860, 860, 860)
                            .addComponent(btnReportsBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(586, 586, 586)
                            .addComponent(btnReports5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(576, 576, 576)
                            .addComponent(btnReports2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblBackgroundReports, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnAdminEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(447, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(btnReports3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnReports4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(165, 165, 165)
                                    .addComponent(btnReportsBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(440, 440, 440)
                            .addComponent(btnReports5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(btnReports2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblBackgroundReports, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminEmployeesActionPerformed
        dlgReportsOrders.setVisible(true);

    }//GEN-LAST:event_btnAdminEmployeesActionPerformed

    private void btnReports2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReports2ActionPerformed

    }//GEN-LAST:event_btnReports2ActionPerformed

    private void btnReports3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReports3ActionPerformed

    }//GEN-LAST:event_btnReports3ActionPerformed

    private void btnReports5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReports5ActionPerformed

    }//GEN-LAST:event_btnReports5ActionPerformed

    private void btnReports4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReports4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReports4ActionPerformed

    private void btnReportsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnReportsBackActionPerformed

    private void btnDlgAdditionsCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgAdditionsCancelActionPerformed
        dlgReportsOrders.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnDlgAdditionsCancelActionPerformed

    private void dlgReportsOrdersWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgReportsOrdersWindowOpened

    }//GEN-LAST:event_dlgReportsOrdersWindowOpened

    private void btnDlgReportsOrdersLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsOrdersLocalActionPerformed

        dlgReportsOrders.setVisible(false);
        // this.setVisible(true);
        generateReport("localOrdersPerRangeDay.jrxml", "Pedidos locales","dates");
    }//GEN-LAST:event_btnDlgReportsOrdersLocalActionPerformed


    private void btnDlgReportsOrdersDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsOrdersDeliveryActionPerformed
        dlgReportsOrders.setVisible(false);
        this.setVisible(true);
        generateReport("orderDeliveryPerRangeDay.jrxml", "Domicilios realizados","dates");
    }//GEN-LAST:event_btnDlgReportsOrdersDeliveryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dlgReportsOrders.setVisible(false);
        this.setVisible(true);
        generateReport("topNeighBorhoodsOrders.jrxml", "Lista de barrios donde más piden","normal");
    }//GEN-LAST:event_jButton2ActionPerformed

    public void generateReport(String nameReport, String title, String typeReport) {
        try {
            Map parameters_report = new HashMap();
            connexion = new Connect();
            if(typeReport.equals("dates")){
            //Creo el calendario
            JDateChooser dateChooser = new JDateChooser();
            //Le doy formato al calendadio
            dateChooser.setDateFormatString("dd-MM-yyyy");
            //Creación de variables para mandar al JOption
            String message;
            SimpleDateFormat changeFormatDate = new SimpleDateFormat("yyyy-MM-dd");
            message = "Por favor seleccione la fecha inicial\n";
            Object[] dateInitParams = {message, dateChooser};
            JOptionPane.showConfirmDialog(null, dateInitParams, "Fecha inicial", JOptionPane.PLAIN_MESSAGE);
            
            String dateInitialStr = changeFormatDate.format(((JDateChooser) dateInitParams[1]).getDate());
            Date dateInitial = changeFormatDate.parse(dateInitialStr);
            message = "Por favor seleccione la fecha final\n";
            Object[] dateFinalParams = {message, dateChooser};
            JOptionPane.showConfirmDialog(null, dateFinalParams, "Fecha final", JOptionPane.PLAIN_MESSAGE);
            String dateFinalStr = changeFormatDate.format(((JDateChooser) dateFinalParams[1]).getDate());
            Date dateFinal = changeFormatDate.parse(dateFinalStr);
            
           
            parameters_report.put("date_initial", dateInitial);
            parameters_report.put("date_final", dateFinal);
            }
            parameters_report.put("logo", getClass().getClassLoader().getResource("resources/images/logoHotWings.jpeg"));
            //  String dir = "src\\reports\\localOrdersPerRangeDay.jrxml.";//windows
            String dir = "src/reports/" + nameReport;
            JOptionPane.showMessageDialog(this, "Por favor espere un momento mientras le informe carga");
            JasperReport reportJasper = JasperCompileManager.compileReport(dir);
            JasperPrint showReport = JasperFillManager.fillReport(reportJasper, parameters_report, connexion.connection);
            JasperViewer jasperViewer = new JasperViewer(showReport, false);
            jasperViewer.setTitle(title);
            jasperViewer.setVisible(true);
            // JasperViewer.viewReport(showReport);

        } catch (JRException ex) {
            System.out.println(ex);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminEmployees;
    private javax.swing.JButton btnDlgAdditionsCancel;
    private javax.swing.JButton btnDlgReportsOrdersDelivery;
    private javax.swing.JButton btnDlgReportsOrdersLocal;
    private javax.swing.JButton btnReports2;
    private javax.swing.JButton btnReports3;
    private javax.swing.JButton btnReports4;
    private javax.swing.JButton btnReports5;
    private javax.swing.JButton btnReportsBack;
    private javax.swing.JDialog dlgReportsOrders;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel lblBackgroundReports;
    private javax.swing.JPanel pnlReportsOrders;
    // End of variables declaration//GEN-END:variables
}
