/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.Connect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.clsDAOOrderDeliveryDetails;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;
import org.pushingpixels.substance.api.shaper.StandardButtonShaper;

/**
 *
 * @author GSG
 */
public class frmReports extends javax.swing.JFrame {

    model.clsDAOOrderDeliveryDetails orderDelivery;
    Map parameters_report;
    controller.Connect connexion;

    /**
     * Creates new form frmReports
     */
    public frmReports() {
        this.setUndecorated(true); //pantalla completa
        //  this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension dim = toolkit.getScreenSize();
        this.setSize(dim.width, dim.height);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReportsOrders.setLocationRelativeTo(this);
        dlgReportsCustomers.setLocationRelativeTo(this);
        dlgReportsOthers.setLocationRelativeTo(this);
        lblBackgroundReports.setSize(dim.width, dim.height);
     //   this.btnReportsOrders.putClientProperty( SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgReportsOrders = new javax.swing.JDialog();
        pnlReportsOrders = new javax.swing.JPanel();
        btnDlgReportsOrdersDelivery = new javax.swing.JButton();
        btnDlgReportsTopNeighborhood = new javax.swing.JButton();
        btnDlgReportsOrdersLocal = new javax.swing.JButton();
        btnDlgReportsOrdersDeliveryPerEmployees = new javax.swing.JButton();
        btnDlgReportsOrdersCancel = new javax.swing.JButton();
        dlgReportsCustomers = new javax.swing.JDialog();
        pnlReportsOrders1 = new javax.swing.JPanel();
        btnDlgReportsCustomersFindOrdersPerCustomer = new javax.swing.JButton();
        btnDlgReportsTopCustomers = new javax.swing.JButton();
        btnDlgReportsCustomersCancel = new javax.swing.JButton();
        dlgReportsOthers = new javax.swing.JDialog();
        pnlReportsOrders2 = new javax.swing.JPanel();
        btnDlgReportsInventoryHistory = new javax.swing.JButton();
        btnDlgReportsOthersCancel = new javax.swing.JButton();
        btnReportsOrders = new javax.swing.JButton();
        btnReportsOthers = new javax.swing.JButton();
        btnReportsCUstomers = new javax.swing.JButton();
        btnReportsBack = new javax.swing.JButton();
        lblBackgroundReports = new javax.swing.JLabel();

        dlgReportsOrders.setTitle("Tipo de reporte ");
        dlgReportsOrders.setMinimumSize(new java.awt.Dimension(711, 423));
        dlgReportsOrders.setSize(new java.awt.Dimension(711, 523));
        dlgReportsOrders.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dlgReportsOrdersWindowOpened(evt);
            }
        });

        pnlReportsOrders.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de reporte", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), java.awt.Color.red)); // NOI18N

        btnDlgReportsOrdersDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDlgReportsOrdersDelivery.setText("<html><center>Pedidos a domicilio<br /> en un rango de días<center>\n</html>\n\n");
        btnDlgReportsOrdersDelivery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDlgReportsOrdersDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsOrdersDeliveryActionPerformed(evt);
            }
        });

        btnDlgReportsTopNeighborhood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDlgReportsTopNeighborhood.setText("<html><center>Lista de barrios <br> donde más piden</center></html>\n\n");
        btnDlgReportsTopNeighborhood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsTopNeighborhoodActionPerformed(evt);
            }
        });

        btnDlgReportsOrdersLocal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDlgReportsOrdersLocal.setText("<html><center>Pedidos locales <br>en un rango de días</center></html>\n");
        btnDlgReportsOrdersLocal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDlgReportsOrdersLocal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDlgReportsOrdersLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsOrdersLocalActionPerformed(evt);
            }
        });

        btnDlgReportsOrdersDeliveryPerEmployees.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDlgReportsOrdersDeliveryPerEmployees.setText("<html><center>Domicilios empleado <br>en un rango de días</center></html> ");
        btnDlgReportsOrdersDeliveryPerEmployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDlgReportsOrdersDeliveryPerEmployees.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDlgReportsOrdersDeliveryPerEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsOrdersDeliveryPerEmployeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReportsOrdersLayout = new javax.swing.GroupLayout(pnlReportsOrders);
        pnlReportsOrders.setLayout(pnlReportsOrdersLayout);
        pnlReportsOrdersLayout.setHorizontalGroup(
            pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsOrdersLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDlgReportsOrdersDeliveryPerEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDlgReportsOrdersLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDlgReportsOrdersDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDlgReportsTopNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlReportsOrdersLayout.setVerticalGroup(
            pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsOrdersLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlgReportsOrdersLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDlgReportsOrdersDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDlgReportsOrdersDeliveryPerEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlReportsOrdersLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnDlgReportsTopNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDlgReportsOrdersCancel.setText("Cancelar");
        btnDlgReportsOrdersCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsOrdersCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgReportsOrdersLayout = new javax.swing.GroupLayout(dlgReportsOrders.getContentPane());
        dlgReportsOrders.getContentPane().setLayout(dlgReportsOrdersLayout);
        dlgReportsOrdersLayout.setHorizontalGroup(
            dlgReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReportsOrdersLayout.createSequentialGroup()
                .addGroup(dlgReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgReportsOrdersLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnDlgReportsOrdersCancel))
                    .addGroup(dlgReportsOrdersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlReportsOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgReportsOrdersLayout.setVerticalGroup(
            dlgReportsOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReportsOrdersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlReportsOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDlgReportsOrdersCancel)
                .addGap(12, 12, 12))
        );

        dlgReportsCustomers.setTitle("Tipo de reporte ");
        dlgReportsCustomers.setMinimumSize(new java.awt.Dimension(550, 423));
        dlgReportsCustomers.setModal(true);
        dlgReportsCustomers.setSize(new java.awt.Dimension(550, 423));
        dlgReportsCustomers.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dlgReportsCustomersWindowOpened(evt);
            }
        });

        pnlReportsOrders1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de reporte", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), java.awt.Color.red)); // NOI18N

        btnDlgReportsCustomersFindOrdersPerCustomer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDlgReportsCustomersFindOrdersPerCustomer.setText("<html><center>Reporte de pedidos<br />de un cliente<center>\n</html>\n\n");
        btnDlgReportsCustomersFindOrdersPerCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDlgReportsCustomersFindOrdersPerCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsCustomersFindOrdersPerCustomerActionPerformed(evt);
            }
        });

        btnDlgReportsTopCustomers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDlgReportsTopCustomers.setText("<html><center>Top clientes que <br>más pedidos hacen</center></html>\n");
        btnDlgReportsTopCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDlgReportsTopCustomers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDlgReportsTopCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsTopCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReportsOrders1Layout = new javax.swing.GroupLayout(pnlReportsOrders1);
        pnlReportsOrders1.setLayout(pnlReportsOrders1Layout);
        pnlReportsOrders1Layout.setHorizontalGroup(
            pnlReportsOrders1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsOrders1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDlgReportsTopCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnDlgReportsCustomersFindOrdersPerCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlReportsOrders1Layout.setVerticalGroup(
            pnlReportsOrders1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsOrders1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pnlReportsOrders1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDlgReportsCustomersFindOrdersPerCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDlgReportsTopCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        btnDlgReportsCustomersCancel.setText("Cancelar");
        btnDlgReportsCustomersCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsCustomersCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgReportsCustomersLayout = new javax.swing.GroupLayout(dlgReportsCustomers.getContentPane());
        dlgReportsCustomers.getContentPane().setLayout(dlgReportsCustomersLayout);
        dlgReportsCustomersLayout.setHorizontalGroup(
            dlgReportsCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReportsCustomersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlgReportsCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgReportsCustomersLayout.createSequentialGroup()
                        .addComponent(btnDlgReportsCustomersCancel)
                        .addGap(455, 455, 455))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgReportsCustomersLayout.createSequentialGroup()
                        .addComponent(pnlReportsOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        dlgReportsCustomersLayout.setVerticalGroup(
            dlgReportsCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReportsCustomersLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlReportsOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDlgReportsCustomersCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgReportsOthers.setTitle("Tipo de reporte ");
        dlgReportsOthers.setMinimumSize(new java.awt.Dimension(750, 523));
        dlgReportsOthers.setModal(true);
        dlgReportsOthers.setSize(new java.awt.Dimension(750, 523));
        dlgReportsOthers.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dlgReportsOthersWindowOpened(evt);
            }
        });

        pnlReportsOrders2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de reporte", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), java.awt.Color.red)); // NOI18N

        btnDlgReportsInventoryHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDlgReportsInventoryHistory.setText("<html><center>Historial de inventario <br>en un rango de días</center></html> ");
        btnDlgReportsInventoryHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDlgReportsInventoryHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDlgReportsInventoryHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsInventoryHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReportsOrders2Layout = new javax.swing.GroupLayout(pnlReportsOrders2);
        pnlReportsOrders2.setLayout(pnlReportsOrders2Layout);
        pnlReportsOrders2Layout.setHorizontalGroup(
            pnlReportsOrders2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsOrders2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDlgReportsInventoryHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(496, Short.MAX_VALUE))
        );
        pnlReportsOrders2Layout.setVerticalGroup(
            pnlReportsOrders2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportsOrders2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(btnDlgReportsInventoryHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        btnDlgReportsOthersCancel.setText("Cancelar");
        btnDlgReportsOthersCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgReportsOthersCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgReportsOthersLayout = new javax.swing.GroupLayout(dlgReportsOthers.getContentPane());
        dlgReportsOthers.getContentPane().setLayout(dlgReportsOthersLayout);
        dlgReportsOthersLayout.setHorizontalGroup(
            dlgReportsOthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReportsOthersLayout.createSequentialGroup()
                .addGroup(dlgReportsOthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgReportsOthersLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnDlgReportsOthersCancel))
                    .addGroup(dlgReportsOthersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlReportsOrders2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        dlgReportsOthersLayout.setVerticalGroup(
            dlgReportsOthersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReportsOthersLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(pnlReportsOrders2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDlgReportsOthersCancel)
                .addGap(12, 12, 12))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generar reportes");
        setMinimumSize(new java.awt.Dimension(1382, 744));
        setSize(new java.awt.Dimension(1382, 744));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReportsOrders.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        btnReportsOrders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReportsOrders.setText("Reportes de pedidos");
        btnReportsOrders.setBorderPainted(false);
        btnReportsOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportsOrders.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportsOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsOrdersActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportsOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 225, 290, 260));

        btnReportsOthers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReportsOthers.setText("Otros");
        btnReportsOthers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportsOthers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportsOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsOthersActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportsOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 225, 290, 260));

        btnReportsCUstomers.setBackground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        btnReportsCUstomers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReportsCUstomers.setText("Reporte Clientes");
        btnReportsCUstomers.setBorderPainted(false);
        btnReportsCUstomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportsCUstomers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportsCUstomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsCUstomersActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportsCUstomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 225, 290, 260));

        btnReportsBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReportsBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/back.png"))); // NOI18N
        btnReportsBack.setText("Volver");
        btnReportsBack.setBorderPainted(false);
        btnReportsBack.setContentAreaFilled(false);
        btnReportsBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportsBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportsBack.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReportsBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportsBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportsBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 605, 120, 110));

        lblBackgroundReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/555.jpg"))); // NOI18N
        getContentPane().add(lblBackgroundReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportsOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsOrdersActionPerformed
        dlgReportsOrders.setVisible(true);

    }//GEN-LAST:event_btnReportsOrdersActionPerformed

    private void btnReportsCUstomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsCUstomersActionPerformed
        dlgReportsCustomers.setVisible(true);
    }//GEN-LAST:event_btnReportsCUstomersActionPerformed

    private void btnReportsOthersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsOthersActionPerformed
        dlgReportsOthers.setVisible(true);
    }//GEN-LAST:event_btnReportsOthersActionPerformed

    private void btnReportsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnReportsBackActionPerformed

    private void btnDlgReportsOrdersCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsOrdersCancelActionPerformed
        dlgReportsOrders.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnDlgReportsOrdersCancelActionPerformed

    private void dlgReportsOrdersWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgReportsOrdersWindowOpened

    }//GEN-LAST:event_dlgReportsOrdersWindowOpened

    private void btnDlgReportsOrdersLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsOrdersLocalActionPerformed

        dlgReportsOrders.setVisible(false);
        // this.setVisible(true);
        parameters_report = new HashMap();
        connexion = new Connect();
        loadDatesCalendarForReports("localOrdersPerRangeDay.jrxml", "Pedidos locales");
    }//GEN-LAST:event_btnDlgReportsOrdersLocalActionPerformed


    private void btnDlgReportsOrdersDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsOrdersDeliveryActionPerformed
        dlgReportsOrders.setVisible(false);
        this.setVisible(true);
        parameters_report = new HashMap();
        connexion = new Connect();
        loadDatesCalendarForReports("orderDeliveryPerRangeDay.jrxml", "Domicilios realizados");
        // generateReport("orderDeliveryPerRangeDay.jrxml", "Domicilios realizados", "dates");
    }//GEN-LAST:event_btnDlgReportsOrdersDeliveryActionPerformed

    private void btnDlgReportsTopNeighborhoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsTopNeighborhoodActionPerformed
        dlgReportsOrders.setVisible(false);
        this.setVisible(true);
        parameters_report = new HashMap();
        connexion = new Connect();
        loadDatesCalendarForReports("topNeighBorhoodsOrders.jrxml", "Lista de barrios donde más piden");

        // generateReport("topNeighBorhoodsOrders.jrxml", "Lista de barrios donde más piden", parameters_report);
    }//GEN-LAST:event_btnDlgReportsTopNeighborhoodActionPerformed

    private void btnDlgReportsCustomersFindOrdersPerCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsCustomersFindOrdersPerCustomerActionPerformed
        dlgReportsCustomers.setVisible(false);
        this.setVisible(true);
        parameters_report = new HashMap();
        connexion = new Connect();
        String phone_customer = JOptionPane.showInputDialog("<html><p><font size=\"5\">Por favor ingrese el número de teléfono del cliente</font></p></html>");
        if (!phone_customer.isEmpty()) {
            parameters_report.put("phone_customer", phone_customer);
            generateReport("OrdersDeliveryPerCustomer.jrxml", "Lista de pedidos por un cliente determinado", parameters_report);

        } else {
            JOptionPane.showMessageDialog(dlgReportsCustomers, "<html><p><font size=\"5\">No ingresó ningún número, por favor vuelva a intentarlo</font></p></html>");
        }

    }//GEN-LAST:event_btnDlgReportsCustomersFindOrdersPerCustomerActionPerformed

    private void btnDlgReportsTopCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsTopCustomersActionPerformed
        dlgReportsCustomers.setVisible(false);
        this.setVisible(true);
        parameters_report = new HashMap();
        connexion = new Connect();
        generateReport("topCustomersOrdersAndTotalOrders.jrxml", "Top clientes que más han pedido", parameters_report);
    }//GEN-LAST:event_btnDlgReportsTopCustomersActionPerformed

    private void btnDlgReportsCustomersCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsCustomersCancelActionPerformed
       dlgReportsCustomers.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnDlgReportsCustomersCancelActionPerformed

    private void dlgReportsCustomersWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgReportsCustomersWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgReportsCustomersWindowOpened

    private void btnDlgReportsInventoryHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsInventoryHistoryActionPerformed
        dlgReportsOthers.setVisible(false);
        this.setVisible(true);
        parameters_report = new HashMap();
        connexion = new Connect();
        loadDatesCalendarForReports("inventoryHistoryTotalPerDates.jrxml", "Historial de inventario por fechas");
    }//GEN-LAST:event_btnDlgReportsInventoryHistoryActionPerformed

    private void btnDlgReportsOthersCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsOthersCancelActionPerformed
       dlgReportsOthers.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnDlgReportsOthersCancelActionPerformed

    private void dlgReportsOthersWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgReportsOthersWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgReportsOthersWindowOpened

    private void btnDlgReportsOrdersDeliveryPerEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgReportsOrdersDeliveryPerEmployeesActionPerformed
        dlgReportsOrders.setVisible(false);
        orderDelivery = new clsDAOOrderDeliveryDetails();
        parameters_report = new HashMap();
        connexion = new Connect();
        ResultSet result = orderDelivery.searchEmployeesJobDelivery();
        JComboBox jcbListEmployees = new JComboBox();
        ArrayList<String> listEmployees_id = new ArrayList<>();
        String employee_id = "";
        try {
            jcbListEmployees.addItem(result.getString(2));
            listEmployees_id.add(result.getString(1));
            while (result.next()) {
                jcbListEmployees.addItem(result.getString(2));
                listEmployees_id.add(result.getString(1));
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        if (listEmployees_id.size() > 0) {

            JOptionPane.showMessageDialog(null, jcbListEmployees, "Por favor seleccione un empleado", JOptionPane.QUESTION_MESSAGE);
            employee_id = listEmployees_id.get(jcbListEmployees.getSelectedIndex());
        }

        if (!employee_id.isEmpty() || !employee_id.equals("")) {
            parameters_report.put("employee_id", employee_id);
            loadDatesCalendarForReports("orderDeliveryPerEmployee.jrxml", "Lista de domicilios llevados por un empleado");
            //    generateReport("OrdersDeliveryPerEmployee.jrxml", "Lista de domicilios llevados por un empleado", parameters_report);
        }else{
            JOptionPane.showMessageDialog(rootPane,"<html><p><font size=\"5\">Debe seleccionar un empleado, por favor repita el proceso.</font></p></html>");

        }

    }//GEN-LAST:event_btnDlgReportsOrdersDeliveryPerEmployeesActionPerformed

    /**
     * Para cargar un reporte que tiene como parámetros una fecha de inicio y
     * una fecha final, se llama a este método, el cual convierte una cadena en
     * un Date y por último este es casteado a timestamp. En la fecha final se
     * aumenta un día con el fin de que tenga en cuenta la fecha final
     *
     * @param nameReport
     * @param title
     */
    public void loadDatesCalendarForReports(String nameReport, String title) {

        //Creo el calendario
        JDateChooser dateChooser = new JDateChooser();
        //Le doy formato al calendadio
        dateChooser.setDateFormatString("dd-MM-yyyy");
        //Creación de variables para mandar al JOption
        String message;
        SimpleDateFormat changeFormatDate = new SimpleDateFormat("yyyy-MM-dd");
        message = "<html><p><font size=\"5\">Por favor seleccione la fecha inicial</font></p></html>\n";
        Object[] dateInitParams = {message, dateChooser};
        JOptionPane.showConfirmDialog(null, dateInitParams, "Fecha inicial", JOptionPane.PLAIN_MESSAGE);
        if (((JDateChooser) dateInitParams[1]).getDate() != null) {
            try {
                String dateInitialStr = changeFormatDate.format(((JDateChooser) dateInitParams[1]).getDate());
                Date dateInitial = changeFormatDate.parse(dateInitialStr);
                message = "<html><p><font size=\"5\">Por favor seleccione la fecha final</font></p></html>\n";
                Object[] dateFinalParams = {message, dateChooser};
                JOptionPane.showConfirmDialog(null, dateFinalParams, "Fecha final", JOptionPane.PLAIN_MESSAGE);
                if (((JDateChooser) dateFinalParams[1]).getDate() != null) {
                    String dateFinalStr = changeFormatDate.format(((JDateChooser) dateFinalParams[1]).getDate());
                    Date dateFinal = changeFormatDate.parse(dateFinalStr);
                    Calendar calendar = Calendar.getInstance();
                    calendar.setTime(dateFinal);
                    calendar.add(Calendar.HOUR, 23);
                    java.sql.Timestamp dateFinalFull = new java.sql.Timestamp(calendar.getTime().getTime());
                    parameters_report.put("date_initial", dateInitial);
                    parameters_report.put("date_final", dateFinalFull);
                    generateReport(nameReport, title, parameters_report);
                } else {
                    JOptionPane.showMessageDialog(this, "<html><p><font size=\"5\">Es necesario que ingrese una fecha final, por favor repita el proceso.</font></p></html>");
                }
            } catch (ParseException ex) {
                System.out.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "<html><p><font size=\"5\">Es necesario que ingrese una fecha inicial, por favor repita el proceso</font></p></html>");
        }

    }

    /**
     * Método encargado de generar el reporte, entra por parámetro el nombre del
     * reporte, el título que llevará y los parámetros que son necesarios para
     * generar el reporte.
     *
     * @param nameReport
     * @param title
     * @param parameters_report
     */
    public void generateReport(String nameReport, String title, Map parameters_report) {
        try {

            parameters_report.put("logo", getClass().getClassLoader().getResource("resources/images/logoHotWings.jpeg"));
  
           // String dir = "src/reports/" + nameReport; //Linux
            String dir = "C:\\HotWings\\reports/" + nameReport; //Para windows
            JOptionPane.showMessageDialog(this, "<html><p><font size=\"5\">Por favor espere un momento mientras el informe carga</font></p></html>");
            JasperReport reportJasper = JasperCompileManager.compileReport(dir);
            JasperPrint showReport = JasperFillManager.fillReport(reportJasper, parameters_report, connexion.connection);
            JasperViewer jasperViewer = new JasperViewer(showReport, false);
            jasperViewer.setTitle(title);
            jasperViewer.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

            jasperViewer.setVisible(true);
            // JasperViewer.viewReport(showReport);

        } catch (JRException ex) {
            System.out.println(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDlgReportsCustomersCancel;
    private javax.swing.JButton btnDlgReportsCustomersFindOrdersPerCustomer;
    private javax.swing.JButton btnDlgReportsInventoryHistory;
    private javax.swing.JButton btnDlgReportsOrdersCancel;
    private javax.swing.JButton btnDlgReportsOrdersDelivery;
    private javax.swing.JButton btnDlgReportsOrdersDeliveryPerEmployees;
    private javax.swing.JButton btnDlgReportsOrdersLocal;
    private javax.swing.JButton btnDlgReportsOthersCancel;
    private javax.swing.JButton btnDlgReportsTopCustomers;
    private javax.swing.JButton btnDlgReportsTopNeighborhood;
    private javax.swing.JButton btnReportsBack;
    private javax.swing.JButton btnReportsCUstomers;
    private javax.swing.JButton btnReportsOrders;
    private javax.swing.JButton btnReportsOthers;
    private javax.swing.JDialog dlgReportsCustomers;
    private javax.swing.JDialog dlgReportsOrders;
    private javax.swing.JDialog dlgReportsOthers;
    private javax.swing.JLabel lblBackgroundReports;
    private javax.swing.JPanel pnlReportsOrders;
    private javax.swing.JPanel pnlReportsOrders1;
    private javax.swing.JPanel pnlReportsOrders2;
    // End of variables declaration//GEN-END:variables
}
